### PR TITLE
Add Source Sans Pro semibold

### PR DESCRIPTION
**Pull request by hbillings**
Dependent on #321

### CODE REVIEW

**Comment by adborden** [comment]
Something is funky here, let me know if you need a hand.

**Comment by hbillings** [comment]
@adborden whoops, sorry about that -- should be good to go now!

EDIT: Hmm, I think actually we're going to need to add this font to the `assets/fonts` folder manually, because if I recall, that folder doesn't get updated with git... and that's where the font needs to live...

**Comment by hbillings** [comment]
Ugh, `da4550d` wasn't supposed to be part of this. I was moving too fast yesterday and got sloppy. :woman_facepalming: (Doesn't really matter where that commit goes -- it's a loosely coupled collection of small changes I made while Aviva and I were pairing. But my apologies.)

**Review by adborden — APPROVED** [review]

**Comment by hbillings** [comment]
Closing to reopen as separate PRs.

**Pull request closed without merging**
