### PR TITLE
Update foia-gov.md

### PR DESCRIPTION
**Pull request by btalebian**
language edits

### CODE REVIEW

**Comment by brockfanning** [comment]
@btalebian This has a "conflict", which means that another pull-request changed this section of text as well. It might be easiest to close this pull-request and start a new one with the desired change. Or if you prefer, you could try the the "Resolve conflicts" button.

**Comment by brockfanning** [comment]
@btalebian @mngardner Just calling your attention to this one. This is one of the pull requests opened a couple weeks back. In the course of merging pull requests, this one ended up with a "conflict". You'll need to either do "resolve conflicts" or close this and open a new one.

**Comment by mngardner** [comment]
@brockfanning - Bobby and I tried looking at this one, but we cant see the conflict or resolve conflict button.  I guess we don't have the necessary user role to see that or edit it.  Can you tell us what the conflict is or go ahead and try doing the resolve conflict and then we can see what the edit might look like before we actually push it.

**Comment by brockfanning** [comment]
@mngardner @btalebian Ah ok, gotcha. In that case I would recommend that you re-do whatever changes you wanted in a new pull request, and then we'll close this one.

**Pull request closed without merging**
